version: 2
jobs:
  build:
    docker:
      - image: z0li/hugo-builder:latest
    working_directory: /src
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:YqqyqmJ6rOhe35usytk4an2NTbyFCV6jdkeyk95VjLQ CircleCI"
      - checkout
      - run: git submodule update --init
      - run: hugo -v -s /src -d /src/public
      - run:
          name: test the generated html files
          command: htmlproofer /src/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
  deploy:
    docker:
      - image: z0li/hugo-builder:latest
    working_directory: /src
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:YqqyqmJ6rOhe35usytk4an2NTbyFCV6jdkeyk95VjLQ CircleCI"
      - checkout
      - run:
          name: push
          command: sh deploy.sh

workflows:
  build_and_test:
    jobs:
      - build
      - deploy
